server:
  port: 8091

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:payment-db}
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-server: ${KAFKA_BROKER:localhost:9092}
    topic:
      payment-success: payment-success
      payment-fail: payment-fail
      orchestrator: orchestrator
    consumer:
      group-id: payment-group
      auto-offset-reset: latest

logging:
  level:
    org:
      apache:
        kafka: OFF